apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wave-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yboikov/argo-test.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
