apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wave-test
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: https://github.com/yboikov/argo-test.git
    targetRevision: HEAD
    path: wave-2
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
