apiVersion: batch/v1
kind: Job
metadata:
  name: wave-2-sleep
  namespace: wave-test
  annotations:
    argocd.argoproj.io/hook: Sync # ← Make it a hook
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: sleep
          image: busybox
          command:
            [
              "sh",
              "-c",
              "echo 'Wave 2 complete, sleeping 15 seconds...'; sleep 15",
            ]
      restartPolicy: Never
  backoffLimit: 0
